# Generated by Django 6.0 on 2026-07-19 21:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_creditwallet_creditledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('apple_app_store', 'Apple App Store'), ('google_play', 'Google Play')], db_index=True, max_length=32)),
                ('external_event_id', models.CharField(max_length=190)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=190)),
                ('signature_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='received', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='billing_event_provider_external_uniq')],
            },
        ),
        migrations.CreateModel(
            name='BillingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('apple_app_store', 'Apple App Store'), ('google_play', 'Google Play')], db_index=True, max_length=32)),
                ('external_product_id', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('subscription', 'Subscription')], default='subscription', max_length=24)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('amount_minor', models.PositiveBigIntegerField(help_text="Price in the currency's minor unit.")),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=16)),
                ('interval_count', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_products', to='accounts.accountplan')),
            ],
            options={
                'ordering': ['provider', 'account_plan__display_order', 'amount_minor'],
            },
        ),
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('apple_app_store', 'Apple App Store'), ('google_play', 'Google Play')], db_index=True, max_length=32)),
                ('external_subscription_id', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('paused', 'Paused'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=24)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.billingproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('apple_app_store', 'Apple App Store'), ('google_play', 'Google Play')], db_index=True, max_length=32)),
                ('external_payment_id', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('charged_back', 'Charged back')], db_index=True, default='pending', max_length=24)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.providersubscription')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openfactura', 'OpenFactura')], default='openfactura', max_length=24)),
                ('kind', models.CharField(choices=[('electronic_receipt', 'Boleta electrónica'), ('exempt_electronic_receipt', 'Boleta electrónica exenta')], default='electronic_receipt', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issuing', 'Issuing'), ('issued', 'Issued'), ('accepted', 'Accepted'), ('accepted_with_objections', 'Accepted with objections'), ('rejected', 'Rejected'), ('voided', 'Voided'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_document_id', models.CharField(blank=True, max_length=190)),
                ('folio', models.CharField(blank=True, max_length=40)),
                ('document_token', models.CharField(blank=True, max_length=190)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tax_document', to='billing.billingpayment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingproduct',
            constraint=models.UniqueConstraint(fields=('provider', 'external_product_id'), name='billing_product_provider_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billingproduct',
            constraint=models.CheckConstraint(condition=models.Q(('interval_count__gt', 0)), name='billing_product_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='providersubscription',
            constraint=models.UniqueConstraint(fields=('provider', 'external_subscription_id'), name='billing_subscription_provider_external_uniq'),
        ),
        migrations.AddConstraint(
            model_name='billingpayment',
            constraint=models.UniqueConstraint(fields=('provider', 'external_payment_id'), name='billing_payment_provider_external_uniq'),
        ),
    ]
