# Generated by Django 6.0.8 on 2026-09-12 01:58

import django.db.models.deletion
from django.db import migrations, models


def seed_offers_for_existing_plans(apps, schema_editor):
    AccountPlan = apps.get_model("accounts", "AccountPlan")
    BillingOffer = apps.get_model("billing", "BillingOffer")
    specs = (
        ("basic-monthly", "basic", 7990, "month", 10),
        ("basic-annual", "basic", 79900, "year", 20),
        ("pro-monthly", "pro", 12990, "month", 10),
        ("pro-annual", "pro", 129900, "year", 20),
    )
    for code, plan_slug, amount_minor, interval, display_order in specs:
        plan = AccountPlan.objects.filter(slug=plan_slug).first()
        if plan is None:
            continue
        BillingOffer.objects.get_or_create(
            code=code,
            defaults={
                "account_plan": plan,
                "currency": "CLP",
                "amount_minor": amount_minor,
                "interval": interval,
                "interval_count": 1,
                "display_order": display_order,
                "metadata": {"bootstrap_source": "billing.migration.0004"},
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountdeletionrecord'),
        ('billing', '0003_appleappaccounttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable commercial offer identifier, for example basic-monthly.', max_length=80, unique=True)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('amount_minor', models.PositiveBigIntegerField(help_text="Canonical price in the currency's minor unit.")),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], max_length=16)),
                ('interval_count', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('public', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_plan__display_order', 'display_order', 'amount_minor'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='billingproduct',
            name='billing_product_provider_external_uniq',
        ),
        migrations.AddField(
            model_name='billingproduct',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], db_index=True, default='live', max_length=16),
        ),
        migrations.AddField(
            model_name='billingproduct',
            name='external_price_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='provider',
            field=models.CharField(choices=[('paddle', 'Paddle'), ('mercado_pago', 'Mercado Pago'), ('apple_app_store', 'Apple App Store'), ('google_play', 'Google Play')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='provider',
            field=models.CharField(choices=[('paddle', 'Paddle'), ('mercado_pago', 'Mercado Pago'), ('apple_app_store', 'Apple App Store'), ('google_play', 'Google Play')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='billingproduct',
            name='provider',
            field=models.CharField(choices=[('paddle', 'Paddle'), ('mercado_pago', 'Mercado Pago'), ('apple_app_store', 'Apple App Store'), ('google_play', 'Google Play')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='providersubscription',
            name='provider',
            field=models.CharField(choices=[('paddle', 'Paddle'), ('mercado_pago', 'Mercado Pago'), ('apple_app_store', 'Apple App Store'), ('google_play', 'Google Play')], db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='billingoffer',
            name='account_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_offers', to='accounts.accountplan'),
        ),
        migrations.AddField(
            model_name='billingproduct',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_products', to='billing.billingoffer'),
        ),
        migrations.RunPython(seed_offers_for_existing_plans, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='billingproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('external_price_id', '')), fields=('provider', 'environment', 'external_product_id'), name='billprod_provider_env_product_uq'),
        ),
        migrations.AddConstraint(
            model_name='billingproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('external_price_id', ''), _negated=True), fields=('provider', 'environment', 'external_price_id'), name='billprod_provider_env_price_uq'),
        ),
        migrations.AddConstraint(
            model_name='billingproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('offer__isnull', False)), fields=('provider', 'environment', 'offer'), name='billprod_active_offer_env_uq'),
        ),
        migrations.AddConstraint(
            model_name='billingoffer',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('public', True)), fields=('account_plan', 'interval', 'interval_count'), name='billing_offer_public_cadence_uq'),
        ),
        migrations.AddConstraint(
            model_name='billingoffer',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='billing_offer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingoffer',
            constraint=models.CheckConstraint(condition=models.Q(('interval_count__gt', 0)), name='billing_offer_interval_positive'),
        ),
    ]
