# Generated by Django 6.0 on 2026-07-01 00:25

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_ref', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable master catalog reference. Not an operational food ID.', unique=True)),
                ('catalog_version', models.CharField(default='v1', help_text='Current master catalog version label for publication/snapshot traceability.', max_length=64)),
                ('display_name', models.CharField(help_text='Human-friendly name for curators and eventual publication.', max_length=255)),
                ('canonical_name', models.CharField(blank=True, help_text='Normalized name for deduplication and matching inside Food Catalog.', max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=160)),
                ('is_branded', models.BooleanField(default=False)),
                ('language', models.CharField(default='es', max_length=10)),
                ('country', models.CharField(blank=True, help_text='Optional country/region code. Example: CL, AR, MX.', max_length=10)),
                ('food_group', models.CharField(blank=True, max_length=120)),
                ('food_subgroup', models.CharField(blank=True, max_length=120)),
                ('protein_g_per_100g', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('carbs_g_per_100g', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fat_g_per_100g', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('calories_kcal_per_100g', models.DecimalField(blank=True, decimal_places=3, help_text='Optional label/source kcal per 100 g. Operational kcal remains snapshot-specific.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fiber_g_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sugar_g_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('saturated_fat_g_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sodium_mg_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('external_candidate', 'External candidate'), ('manual_candidate', 'Manual candidate'), ('brand_submitted', 'Brand submitted'), ('normalized', 'Normalized'), ('pending_review', 'Pending review'), ('needs_more_evidence', 'Needs more evidence'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('published', 'Published'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='manual_candidate', max_length=40)),
                ('source_type', models.CharField(choices=[('natural_verified', 'Natural verified'), ('brand_submitted', 'Brand submitted'), ('user_created', 'User created'), ('external_temporary', 'External temporary'), ('admin_import', 'Admin import')], default='admin_import', help_text='High-level origin category for curation and governance.', max_length=40)),
                ('data_quality_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_foods', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_catalog_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog food',
                'verbose_name_plural': 'Catalog foods',
                'ordering': ['display_name', 'brand_name', 'country'],
            },
        ),
        migrations.CreateModel(
            name='CatalogFoodAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, max_length=255)),
                ('alias_type', models.CharField(choices=[('search', 'Search'), ('common', 'Common'), ('localized', 'Localized')], default='search', max_length=30)),
                ('language', models.CharField(default='es', max_length=10)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='food_catalog.catalogfood')),
            ],
            options={
                'verbose_name': 'Catalog food alias',
                'verbose_name_plural': 'Catalog food aliases',
                'ordering': ['catalog_food', 'language', 'country', '-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogFoodPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('grams', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('source', models.CharField(blank=True, max_length=80)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='food_catalog.catalogfood')),
            ],
            options={
                'verbose_name': 'Catalog food portion',
                'verbose_name_plural': 'Catalog food portions',
                'ordering': ['catalog_food', '-is_default', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CatalogImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('natural_verified', 'Natural verified'), ('brand_submitted', 'Brand submitted'), ('user_created', 'User created'), ('external_temporary', 'External temporary'), ('admin_import', 'Admin import')], max_length=40)),
                ('source_name', models.CharField(max_length=160)),
                ('source_version', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed')], default='pending', max_length=40)),
                ('is_dry_run', models.BooleanField(default=False)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('summary_payload', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catalog import batch',
                'verbose_name_plural': 'Catalog import batches',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source_type', 'status'], name='cat_batch_src_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatalogFoodSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('natural_verified', 'Natural verified'), ('brand_submitted', 'Brand submitted'), ('user_created', 'User created'), ('external_temporary', 'External temporary'), ('admin_import', 'Admin import')], max_length=40)),
                ('source_name', models.CharField(max_length=160)),
                ('source_food_id', models.CharField(blank=True, max_length=160)),
                ('source_dataset', models.CharField(blank=True, max_length=160)),
                ('source_version', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('raw_payload_hash', models.CharField(blank=True, max_length=128)),
                ('normalized_payload_hash', models.CharField(blank=True, max_length=128)),
                ('license_name', models.CharField(blank=True, max_length=160)),
                ('license_status', models.CharField(choices=[('allowed', 'Allowed'), ('needs_review', 'Needs review'), ('restricted', 'Restricted'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('attribution', models.TextField(blank=True)),
                ('evidence_payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='food_catalog.catalogfood')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_sources', to='food_catalog.catalogimportbatch')),
            ],
            options={
                'verbose_name': 'Catalog food source',
                'verbose_name_plural': 'Catalog food sources',
                'ordering': ['catalog_food', 'source_name', 'source_food_id'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogfood',
            index=models.Index(fields=['status', 'source_type'], name='catalog_food_status_source_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogfood',
            index=models.Index(fields=['canonical_name'], name='catalog_food_canonical_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogfood',
            index=models.Index(fields=['display_name'], name='catalog_food_display_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogfood',
            constraint=models.UniqueConstraint(condition=models.Q(('canonical_name', ''), _negated=True), fields=('canonical_name', 'brand_name', 'country'), name='unique_catalog_food_canonical_brand_country'),
        ),
        migrations.AddConstraint(
            model_name='catalogfoodalias',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_name', ''), _negated=True), fields=('catalog_food', 'normalized_name', 'language', 'country'), name='unique_catalog_food_alias_language_country'),
        ),
        migrations.AddConstraint(
            model_name='catalogfoodportion',
            constraint=models.UniqueConstraint(fields=('catalog_food', 'label'), name='unique_catalog_food_portion_label'),
        ),
        migrations.AddConstraint(
            model_name='catalogfoodsource',
            constraint=models.UniqueConstraint(condition=models.Q(('source_food_id', ''), _negated=True), fields=('source_name', 'source_food_id'), name='unique_catalog_food_source_external_id'),
        ),
    ]
