# Generated by ChatGPT for Food Catalog Launch Readiness FC-04.

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogfood",
            name="preparation_state",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("raw", "Raw"),
                    ("cooked", "Cooked"),
                    ("dry", "Dry"),
                    ("hydrated", "Hydrated"),
                    ("ready_to_eat", "Ready to eat"),
                ],
                default="unknown",
                help_text=(
                    "Semantic state used for curation and solver safety. Example: raw, "
                    "cooked, dry, hydrated or ready_to_eat. Avoids mixing raw/cooked data."
                ),
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="catalogfood",
            name="solver_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If true, this master food is eligible to become an operational "
                    "solver candidate after publication/snapshot."
                ),
            ),
        ),
        migrations.AddField(
            model_name="catalogfood",
            name="solver_min_portion_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Optional explicit minimum portion for future optimization.",
                max_digits=8,
                null=True,
                validators=[MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AddField(
            model_name="catalogfood",
            name="solver_max_portion_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Optional explicit maximum portion for future optimization.",
                max_digits=8,
                null=True,
                validators=[MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AddField(
            model_name="catalogfood",
            name="solver_portion_step_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Optional explicit portion increment for future optimization.",
                max_digits=8,
                null=True,
                validators=[MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AddIndex(
            model_name="catalogfood",
            index=models.Index(
                fields=["solver_enabled", "status"],
                name="catalog_food_solver_status_idx",
            ),
        ),
    ]
