# Generated by Django 6.0 on 2026-07-02 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_catalog', '0004_alter_catalogimportbatch_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCurationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fatsecret', 'FatSecret'), ('open_food_facts', 'Open Food Facts')], max_length=40)),
                ('external_food_id', models.CharField(blank=True, max_length=160)),
                ('external_serving_id', models.CharField(blank=True, max_length=160)),
                ('display_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('attribution_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_review', 'In review'), ('needs_more_evidence', 'Needs more evidence'), ('approved_for_curation', 'Approved for curation'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='queued', max_length=40)),
                ('reason', models.CharField(choices=[('external_selected', 'External selected'), ('external_demand', 'External demand'), ('manual_review', 'Manual review')], default='external_demand', max_length=40)),
                ('priority', models.PositiveSmallIntegerField(default=50, help_text='Curator priority from 0 to 100. Higher means more urgent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('seen_count_at_creation', models.PositiveIntegerField(default=0)),
                ('selected_count_at_creation', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_curation_candidates', to=settings.AUTH_USER_MODEL)),
                ('external_reference', models.ForeignKey(blank=True, help_text='External lookup reference that triggered this curation work item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_candidates', to='food_catalog.externalfoodreference')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_catalog_curation_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalog curation candidate',
                'verbose_name_plural': 'Catalog curation candidates',
                'ordering': ['-priority', 'status', 'display_name'],
                'indexes': [models.Index(fields=['status', 'priority'], name='cat_curation_status_prio_idx'), models.Index(fields=['provider', 'external_food_id'], name='cat_curation_provider_food_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_reference__isnull', False)), fields=('external_reference',), name='unique_catalog_curation_external_ref')],
            },
        ),
    ]
