# Generated by Django 6.0 on 2026-08-12 20:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_catalog', '0009_catalogimportsourcepolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCapabilityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('schema_version', models.CharField(default='v1', max_length=64)),
                ('label', models.CharField(max_length=160)),
                ('data_type', models.CharField(max_length=40)),
                ('nature', models.CharField(choices=[('factual', 'Factual'), ('operational', 'Operational'), ('semantic', 'Semantic'), ('derived', 'Derived'), ('commercial_context', 'Commercial context')], max_length=40)),
                ('maturity', models.CharField(choices=[('experimental', 'Experimental'), ('candidate', 'Candidate'), ('stable', 'Stable'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], default='experimental', max_length=30)),
                ('consumers', models.JSONField(blank=True, default=list)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
                ('authority_requirement', models.CharField(choices=[('rule_auto_apply', 'Rule auto-apply'), ('internal_review', 'Internal review'), ('expert_review', 'Expert review'), ('external_evidence_required', 'External evidence required'), ('legal_review_required', 'Legal review required')], max_length=40)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('scope_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key', 'schema_version'],
                'constraints': [models.UniqueConstraint(fields=('key', 'schema_version'), name='unique_catalog_capability_version')],
            },
        ),
        migrations.CreateModel(
            name='CatalogEnrichmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('environment', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('scope_payload', models.JSONField(default=dict)),
                ('instruction', models.TextField(blank=True)),
                ('executor_kind', models.CharField(default='codex_assisted', max_length=40)),
                ('contract_version', models.CharField(default='catalog-enrichment.v1', max_length=64)),
                ('policy_version', models.CharField(default='catalog-enrichment-policy.v1', max_length=64)),
                ('input_sha256', models.CharField(max_length=64)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('manifest_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('dry_run_valid', 'Dry Run Valid'), ('dry_run_failed', 'Dry Run Failed'), ('approved_for_apply', 'Approved For Apply'), ('applied', 'Applied'), ('partially_applied', 'Partially Applied'), ('reverted', 'Reverted'), ('cancelled', 'Cancelled')], default='draft', max_length=40)),
                ('total_proposals', models.PositiveIntegerField(default=0)),
                ('valid_proposals', models.PositiveIntegerField(default=0)),
                ('applied_proposals', models.PositiveIntegerField(default=0)),
                ('failed_proposals', models.PositiveIntegerField(default=0)),
                ('dry_run_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_catalog_enrichment_batches', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_catalog_enrichment_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogFieldProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120)),
                ('expected_food_updated_at', models.DateTimeField()),
                ('current_value', models.JSONField(blank=True, null=True)),
                ('proposed_value', models.JSONField(blank=True, null=True)),
                ('nature', models.CharField(choices=[('factual', 'Factual'), ('operational', 'Operational'), ('semantic', 'Semantic'), ('derived', 'Derived'), ('commercial_context', 'Commercial context')], max_length=40)),
                ('provenance', models.JSONField(default=list)),
                ('consumers', models.JSONField(default=list)),
                ('maturity', models.CharField(choices=[('experimental', 'Experimental'), ('candidate', 'Candidate'), ('stable', 'Stable'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], max_length=30)),
                ('generation_method', models.CharField(default='codex_assisted', max_length=40)),
                ('authority_requirement', models.CharField(choices=[('rule_auto_apply', 'Rule auto-apply'), ('internal_review', 'Internal review'), ('expert_review', 'Expert review'), ('external_evidence_required', 'External evidence required'), ('legal_review_required', 'Legal review required')], max_length=40)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('assessment_status', models.CharField(choices=[('unassessed', 'Unassessed'), ('proposed', 'Proposed'), ('confirmed_value', 'Confirmed value'), ('confirmed_none', 'Confirmed none'), ('not_applicable', 'Not applicable'), ('conflicting_evidence', 'Conflicting evidence'), ('superseded', 'Superseded')], max_length=40)),
                ('profile_key', models.CharField(blank=True, max_length=100)),
                ('policy_version', models.CharField(blank=True, max_length=80)),
                ('rationale', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evidence_references', models.JSONField(blank=True, default=list)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='food_catalog.catalogenrichmentbatch')),
                ('capability_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='food_catalog.catalogcapabilitydefinition')),
                ('catalog_food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrichment_proposals', to='food_catalog.catalogfood')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_catalog_field_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch', 'catalog_food', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogEnrichmentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('apply', 'Apply'), ('revert', 'Revert')], max_length=20)),
                ('value_before', models.JSONField(blank=True, null=True)),
                ('value_after', models.JSONField(blank=True, null=True)),
                ('food_updated_at_before', models.DateTimeField()),
                ('food_updated_at_after', models.DateTimeField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_enrichment_changes', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='food_catalog.catalogenrichmentbatch')),
                ('catalog_food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrichment_changes', to='food_catalog.catalogfood')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='food_catalog.catalogfieldproposal')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogFoodCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('assessment_status', models.CharField(choices=[('unassessed', 'Unassessed'), ('proposed', 'Proposed'), ('confirmed_value', 'Confirmed value'), ('confirmed_none', 'Confirmed none'), ('not_applicable', 'Not applicable'), ('conflicting_evidence', 'Conflicting evidence'), ('superseded', 'Superseded')], default='unassessed', max_length=40)),
                ('provenance', models.JSONField(blank=True, default=list)),
                ('generation_method', models.CharField(blank=True, max_length=40)),
                ('evidence_references', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('policy_version', models.CharField(blank=True, max_length=80)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_values', to='food_catalog.catalogfood')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_capability_decisions', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_values', to='food_catalog.catalogcapabilitydefinition')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogClientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.SlugField(max_length=80)),
                ('requirement_version', models.CharField(max_length=64)),
                ('is_required', models.BooleanField(default=False)),
                ('absence_behavior', models.CharField(blank=True, max_length=80)),
                ('operational_destination', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_requirements', to='food_catalog.catalogcapabilitydefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client_key', 'requirement_version', 'capability'), name='unique_catalog_client_requirement')],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogfieldproposal',
            constraint=models.UniqueConstraint(fields=('batch', 'catalog_food', 'field_name'), name='unique_catalog_batch_food_field'),
        ),
        migrations.AddConstraint(
            model_name='catalogfoodcapability',
            constraint=models.UniqueConstraint(fields=('catalog_food', 'definition'), name='unique_catalog_food_capability'),
        ),
    ]
