# Generated by Django 6.0.8 on 2026-09-17 18:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_catalog', '0010_catalogcapabilitydefinition_catalogenrichmentbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogfood',
            name='imported_release_version',
            field=models.CharField(blank=True, help_text='Authority release that last synchronized this mirror row.', max_length=80),
        ),
        migrations.AddField(
            model_name='catalogfood',
            name='is_release_managed',
            field=models.BooleanField(default=False, help_text='True only in consumer environments when this row is a read-only mirror of a Food Catalog release.'),
        ),
        migrations.CreateModel(
            name='CatalogRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.CharField(max_length=80, unique=True)),
                ('schema_version', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='candidate', max_length=20)),
                ('role', models.CharField(choices=[('authority', 'Authority'), ('replica', 'Replica')], default='authority', max_length=20)),
                ('previous_version', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('food_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_catalog_releases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalog_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'role'], name='cat_release_status_role_idx')],
            },
        ),
    ]
