# Generated by Django 6.0 on 2026-01-27 15:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_meal_pending_dailyplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlanShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailyplan_shares_received', to=settings.AUTH_USER_MODEL)),
                ('dailyplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='notas.dailyplan')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyplan_shares_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recipient_email', 'dailyplan')},
            },
        ),
    ]
