# Generated by ChatGPT patch for proposal list ordering.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0025_dailyplan_meal_list_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionproposal",
            name="list_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
