# Generated by ChatGPT patch for food list ordering.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0026_nutritionproposal_list_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="list_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
