# Generated by ChatGPT patch for inbox favorites.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0027_food_list_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplanshare",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mealshare",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
