# Generated by ChatGPT

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0031_simplify_proposal_statuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient_email", models.EmailField(max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dismissed", models.BooleanField(default=False)),
                ("removed", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                ("subject", models.CharField(blank=True, max_length=160)),
                ("accepted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="food_shares_received", to=settings.AUTH_USER_MODEL)),
                ("food", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="notas.food")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="food_shares_sent", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("recipient_email", "food")},
            },
        ),
        migrations.CreateModel(
            name="DailyPlanMealShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient_email", models.EmailField(max_length=254)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dismissed", models.BooleanField(default=False)),
                ("removed", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True)),
                ("subject", models.CharField(blank=True, max_length=160)),
                ("accepted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="dailyplanmeal_shares_received", to=settings.AUTH_USER_MODEL)),
                ("dailyplan_meal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="notas.dailyplanmeal")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dailyplanmeal_shares_sent", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("recipient_email", "dailyplan_meal")},
            },
        ),
    ]
