# Generated by Django 6.0 on 2026-06-19 00:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_weekly_program_fields(apps, schema_editor):
    Program = apps.get_model("notas", "Program")
    ProgramDay = apps.get_model("notas", "ProgramDay")

    for program in Program.objects.all():
        program_days = list(
            ProgramDay.objects
            .filter(program_id=program.id)
            .order_by("date", "id")
        )

        if program.start_date and program.end_date:
            duration_days = max((program.end_date - program.start_date).days + 1, 1)
            duration_weeks = max((duration_days + 6) // 7, 1)
        else:
            duration_weeks = max((len(program_days) + 6) // 7, 1)

        used_slots = set()

        for index, program_day in enumerate(program_days):
            if program_day.date and program.start_date:
                offset = max((program_day.date - program.start_date).days, 0)
                week_number = offset // 7 + 1
                day_number = offset % 7 + 1
            else:
                week_number = index // 7 + 1
                day_number = index % 7 + 1

            while (week_number, day_number) in used_slots:
                day_number += 1
                if day_number > 7:
                    week_number += 1
                    day_number = 1

            used_slots.add((week_number, day_number))
            duration_weeks = max(duration_weeks, week_number)

            program_day.week_number = week_number
            program_day.day_number = day_number
            program_day.save(update_fields=["week_number", "day_number"])

        program.duration_weeks = max(duration_weeks, 1)
        program.save(update_fields=["duration_weeks"])


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0032_food_dpm_shares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['list_order', '-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='programday',
            options={'ordering': ['week_number', 'day_number', 'id']},
        ),
        migrations.AddField(
            model_name='program',
            name='duration_weeks',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='program',
            name='list_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programday',
            name='day_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programday',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('system', 'System'), ('mcp', 'MCP'), ('program', 'Program')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programday',
            name='dailyplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_slots', to='notas.dailyplan'),
        ),
        migrations.AlterField(
            model_name='programday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_weekly_program_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='programday',
            name='day_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='programday',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(fields=('program', 'week_number', 'day_number'), name='unique_program_week_day'),
        ),
        migrations.AddField(
            model_name='programshare',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_shares_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programshare',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='notas.program'),
        ),
        migrations.AddField(
            model_name='programshare',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_shares_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='programshare',
            unique_together={('recipient_email', 'program')},
        ),
    ]
