# Generated by Django 6.0 on 2026-06-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0039_ainutritionchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='catalog_food_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Optional trace to food_catalog.CatalogFood. This is not a ForeignKey and is never an operational food ID for Meals, Solver or MCP.', null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='catalog_food_ref',
            field=models.UUIDField(blank=True, db_index=True, help_text='Stable Food Catalog reference copied when this Food is created/refreshed from a catalog snapshot.', null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='catalog_snapshot_created_at',
            field=models.DateTimeField(blank=True, help_text='Date/time when the Food Catalog snapshot was materialized into notas.Food.', null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='catalog_snapshot_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Auditable payload copied from Food Catalog at snapshot time.'),
        ),
        migrations.AddField(
            model_name='food',
            name='catalog_snapshot_version',
            field=models.CharField(blank=True, help_text='Food Catalog version label used to create or refresh this operational snapshot.', max_length=64),
        ),
        migrations.AddField(
            model_name='food',
            name='catalog_sync_status',
            field=models.CharField(choices=[('none', 'None'), ('snapshot', 'Snapshot'), ('stale', 'Stale'), ('unlinked', 'Unlinked')], default='none', help_text='Internal sync state for the optional Food Catalog trace.', max_length=24),
        ),
    ]
