# Generated by ChatGPT for Food Catalog Launch Readiness FC-04.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0040_food_catalog_snapshot_trace"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="preparation_state",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("raw", "Raw"),
                    ("cooked", "Cooked"),
                    ("dry", "Dry"),
                    ("hydrated", "Hydrated"),
                    ("ready_to_eat", "Ready to eat"),
                ],
                default="unknown",
                help_text=(
                    "Copied semantic state from Food Catalog when available. Used to avoid "
                    "mixing raw/cooked/dry/hydrated foods in future optimization flows."
                ),
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="food",
            name="solver_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether this operational food may be used by future nutrition solver candidates.",
            ),
        ),
    ]
