# Generated by ChatGPT for ONB01 body metrics base.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0041_food_solver_readiness_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Birth date used to calculate nutritional age dynamically.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                ],
                default="",
                help_text="Sex value used by nutritional energy-estimation formulas.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="height_cm",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Height in centimeters captured by the nutrition onboarding.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the required onboarding flow was completed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="onboarding_version",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Latest onboarding version completed by the user.",
            ),
        ),
        migrations.AddField(
            model_name="weightlog",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("onboarding", "Onboarding"),
                    ("import", "Import"),
                ],
                default="manual",
                help_text="Origin of this body-weight metric entry.",
                max_length=30,
            ),
        ),
    ]
