# Generated by Django 6.0 on 2026-07-19 18:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0043_food_solver_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone_name',
            field=models.CharField(default='UTC', help_text='IANA timezone used as the default for user-local scheduling.', max_length=64),
        ),
        migrations.CreateModel(
            name='ProgramCalendarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name_snapshot', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('daily_notification_time', models.TimeField(default=datetime.time(7, 0))),
                ('daily_notifications_enabled', models.BooleanField(default=True)),
                ('meal_notifications_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('active', 'Activa'), ('paused', 'Pausada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], db_index=True, default='scheduled', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendarizations', to='notas.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_calendarizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarizedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField()),
                ('week_number', models.PositiveSmallIntegerField()),
                ('day_number', models.PositiveSmallIntegerField()),
                ('source_program_day_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_dailyplan_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('plan_snapshot', models.JSONField(blank=True, null=True)),
                ('snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendarization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='notas.programcalendarization')),
            ],
            options={
                'ordering': ['calendar_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('daily_plan', 'Daily plan'), ('meal_reminder', 'Meal reminder')], max_length=30)),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('meal_snapshot_key', models.CharField(blank=True, max_length=80)),
                ('local_scheduled_date', models.DateField()),
                ('local_scheduled_time', models.TimeField()),
                ('timezone_name', models.CharField(max_length=64)),
                ('scheduled_for_utc', models.DateTimeField(db_index=True)),
                ('available_until_utc', models.DateTimeField()),
                ('dst_resolution', models.CharField(default='exact', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('skip_reason', models.CharField(blank=True, max_length=80)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendarization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='notas.programcalendarization')),
                ('calendarized_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='notas.calendarizedday')),
            ],
            options={
                'ordering': ['scheduled_for_utc', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('endpoint_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('p256dh_key', models.CharField(max_length=255)),
                ('auth_key', models.CharField(max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notas.schedulednotificationevent')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notas.webpushsubscription')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='programcalendarization',
            index=models.Index(fields=['user', 'status', 'start_date'], name='cal_user_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='programcalendarization',
            index=models.Index(fields=['status', 'end_date'], name='cal_status_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='programcalendarization',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('scheduled', 'active', 'paused'))), fields=('user',), name='cal_one_current_per_user'),
        ),
        migrations.AddConstraint(
            model_name='programcalendarization',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='cal_end_not_before_start'),
        ),
        migrations.AddIndex(
            model_name='calendarizedday',
            index=models.Index(fields=['calendarization', 'calendar_date'], name='cal_day_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarizedday',
            constraint=models.UniqueConstraint(fields=('calendarization', 'calendar_date'), name='cal_unique_calendar_date'),
        ),
        migrations.AddConstraint(
            model_name='calendarizedday',
            constraint=models.UniqueConstraint(fields=('calendarization', 'week_number', 'day_number'), name='cal_unique_program_slot'),
        ),
        migrations.AddConstraint(
            model_name='calendarizedday',
            constraint=models.CheckConstraint(condition=models.Q(('day_number__gte', 1), ('day_number__lte', 7)), name='cal_day_number_range'),
        ),
        migrations.AddIndex(
            model_name='schedulednotificationevent',
            index=models.Index(fields=['status', 'scheduled_for_utc'], name='push_event_due_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulednotificationevent',
            index=models.Index(fields=['calendarization', 'status'], name='push_event_cal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='webpushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='push_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'created_at'], name='push_delivery_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'subscription_fingerprint'), name='push_unique_event_device'),
        ),
    ]
