# Generated by Django 6.0 on 2026-08-06 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0047_oauth_device_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarizationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('energy_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hunger_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('training_performance_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000)),
                ('summary_snapshot', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendarization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='notas.programcalendarization')),
            ],
            options={
                'ordering': ['-period_end', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarizationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('before_snapshot', models.JSONField(default=dict)),
                ('after_snapshot', models.JSONField(default=dict)),
                ('rationale', models.CharField(max_length=1000)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendarization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='notas.programcalendarization')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='notas.calendarizationreview')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarizedMealExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_snapshot_key', models.CharField(max_length=80)),
                ('action', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('reset', 'Reset')], max_length=20)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendarized_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_execution_events', to='notas.calendarizedday')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarizationMeasurementContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calendarization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_contexts', to='notas.programcalendarization')),
                ('calendarized_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement_contexts', to='notas.calendarizedday')),
                ('weight_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendarization_contexts', to='notas.weightlog')),
            ],
            options={
                'ordering': ['weight_log__date', 'id'],
                'indexes': [models.Index(fields=['calendarization', 'created_at'], name='cal_measure_context_idx')],
                'constraints': [models.UniqueConstraint(fields=('calendarization', 'weight_log'), name='cal_unique_measure_context')],
            },
        ),
        migrations.AddIndex(
            model_name='calendarizationreview',
            index=models.Index(fields=['calendarization', 'period_end'], name='cal_review_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarizationreview',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='cal_review_period_valid'),
        ),
        migrations.AddIndex(
            model_name='calendarizationrevision',
            index=models.Index(fields=['calendarization', 'status', 'effective_from'], name='cal_revision_status_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarizedmealexecution',
            index=models.Index(fields=['calendarized_day', 'created_at'], name='cal_meal_exec_day_idx'),
        ),
    ]
