# Generated by Django 6.0 on 2026-08-06 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0048_calendarized_execution_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLabelCaptureReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('ocr_engine', models.CharField(max_length=80)),
                ('ocr_engine_version', models.CharField(blank=True, max_length=40)),
                ('detected_basis', models.CharField(choices=[('per_100g', 'Per 100 g'), ('per_serving', 'Per serving'), ('manual', 'Manual review')], max_length=24)),
                ('serving_size_g', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('declared_energy_kcal_per_100g', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('field_confidence', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('confirmed_payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_capture_receipt', to='notas.food')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['ocr_engine', 'created_at'], name='food_label_ocr_engine_idx')],
            },
        ),
    ]
