# Generated by Django 6.0 on 2026-08-06 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0049_foodlabelcapturereceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('web_push', 'Web Push'), ('apns', 'Apple Push Notification service')], default='web_push', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplePushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=200)),
                ('token_fingerprint', models.CharField(max_length=64, unique=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apple_push_subscription', to='notas.oauthdevicesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='apple_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notas.applepushsubscription'),
        ),
        migrations.AddIndex(
            model_name='applepushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='apns_user_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('apple_subscription__isnull', True), ('channel', 'web_push')), models.Q(('channel', 'apns'), ('subscription__isnull', True)), _connector='OR'), name='push_delivery_channel_target'),
        ),
    ]
