# Generated by Django 6.0.8 on 2026-09-11 22:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0055_food_label_per_100ml_basis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject_type', models.CharField(choices=[('daily_plan', 'Daily plan'), ('food', 'Food'), ('meal', 'Meal'), ('program', 'Program')], max_length=24)),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('snapshot_schema_version', models.CharField(max_length=48)),
                ('visibility', models.CharField(choices=[('unlisted', 'Unlisted')], default='unlisted', max_length=16)),
                ('claim_policy', models.CharField(choices=[('none', 'No claims'), ('single', 'Single claim'), ('multiple', 'Multiple claims')], default='multiple', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_resources_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('claimed', 'Claimed'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_invitations_received', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='notas.shareresource')),
            ],
        ),
        migrations.CreateModel(
            name='ShareClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('email', 'Email'), ('link', 'Link')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_claims', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='notas.shareinvitation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='notas.shareresource')),
            ],
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_inbox_items', to=settings.AUTH_USER_MODEL)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_item', to='notas.shareclaim')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='notas.shareresource')),
            ],
        ),
        migrations.AddIndex(
            model_name='shareresource',
            index=models.Index(fields=['sender', 'status'], name='share_res_sender_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shareresource',
            index=models.Index(fields=['subject_type', 'source_object_id'], name='share_res_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='shareinvitation',
            constraint=models.UniqueConstraint(fields=('resource', 'recipient_email'), name='share_invite_resource_email_uniq'),
        ),
        migrations.AddConstraint(
            model_name='shareclaim',
            constraint=models.UniqueConstraint(fields=('resource', 'user'), name='share_claim_resource_user_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inboxitem',
            constraint=models.UniqueConstraint(fields=('owner', 'resource'), name='inbox_owner_resource_uniq'),
        ),
    ]
