# Generated by Django 6.0.8 on 2026-09-11 23:09

from django.db import migrations, models

SNAPSHOT_VERSION = "sharing.snapshot.v1"


def _number(value):
    return round(float(value or 0), 2)


def _nutrition(protein, carbs, fat):
    protein = _number(protein)
    carbs = _number(carbs)
    fat = _number(fat)
    return {
        "calories": _number(protein * 4 + carbs * 4 + fat * 9),
        "protein_grams": protein,
        "carbs_grams": carbs,
        "fat_grams": fat,
    }


def backfill_accepted_dailyplan_shares(apps, schema_editor):
    DailyPlanShare = apps.get_model("notas", "DailyPlanShare")
    DailyPlanMeal = apps.get_model("notas", "DailyPlanMeal")
    MealFood = apps.get_model("notas", "MealFood")
    ShareResource = apps.get_model("notas", "ShareResource")
    ShareInvitation = apps.get_model("notas", "ShareInvitation")
    ShareClaim = apps.get_model("notas", "ShareClaim")
    InboxItem = apps.get_model("notas", "InboxItem")

    for legacy in DailyPlanShare.objects.exclude(accepted_by_id=None).select_related("dailyplan").iterator():
        reference = f"dailyplan:{legacy.id}"
        resource, created = ShareResource.objects.get_or_create(
            legacy_reference=reference,
            defaults={
                "sender_id": legacy.sender_id,
                "subject_type": "daily_plan",
                "source_object_id": legacy.dailyplan_id,
                "snapshot": {},
                "snapshot_schema_version": SNAPSHOT_VERSION,
                "claim_policy": "single",
                "status": "active",
            },
        )
        if not created:
            continue

        meals = []
        plan_protein = plan_carbs = plan_fat = 0.0
        food_count = 0
        rows = DailyPlanMeal.objects.filter(dailyplan_id=legacy.dailyplan_id).select_related("meal").order_by(
            "order", "id"
        )
        for dailyplan_meal in rows:
            foods = []
            meal_protein = meal_carbs = meal_fat = 0.0
            for meal_food in MealFood.objects.filter(meal_id=dailyplan_meal.meal_id).select_related("food").order_by(
                "order", "id"
            ):
                factor = float(meal_food.quantity or 0) / 100
                protein = float(meal_food.food.protein or 0) * factor
                carbs = float(meal_food.food.carbs or 0) * factor
                fat = float(meal_food.food.fat or 0) * factor
                food_nutrition = _nutrition(protein, carbs, fat)
                foods.append(
                    {
                        "name": meal_food.food.name,
                        "quantity_grams": _number(meal_food.quantity),
                        "nutrition": food_nutrition,
                    }
                )
                meal_protein += food_nutrition["protein_grams"]
                meal_carbs += food_nutrition["carbs_grams"]
                meal_fat += food_nutrition["fat_grams"]
                food_count += 1
            meal_nutrition = _nutrition(meal_protein, meal_carbs, meal_fat)
            plan_protein += meal_nutrition["protein_grams"]
            plan_carbs += meal_nutrition["carbs_grams"]
            plan_fat += meal_nutrition["fat_grams"]
            meals.append(
                {
                    "name": dailyplan_meal.meal.name,
                    "time": dailyplan_meal.hour.isoformat(timespec="minutes") if dailyplan_meal.hour else None,
                    "nutrition": meal_nutrition,
                    "foods": foods,
                }
            )
        resource.snapshot = {
            "schema_version": SNAPSHOT_VERSION,
            "subject": {"type": "daily_plan", "title": legacy.dailyplan.name},
            "summary": {"meal_count": len(meals), "food_count": food_count},
            "nutrition": _nutrition(plan_protein, plan_carbs, plan_fat),
            "meals": meals,
        }
        resource.save(update_fields=["snapshot", "updated_at"])
        ShareResource.objects.filter(pk=resource.pk).update(created_at=legacy.created_at, updated_at=legacy.created_at)

        invitation = ShareInvitation.objects.create(
            resource_id=resource.id,
            recipient_email=legacy.recipient_email,
            recipient_user_id=legacy.accepted_by_id,
            status="claimed",
            claimed_at=legacy.created_at,
        )
        ShareInvitation.objects.filter(pk=invitation.pk).update(
            created_at=legacy.created_at,
            updated_at=legacy.created_at,
        )
        claim = ShareClaim.objects.create(
            resource_id=resource.id,
            user_id=legacy.accepted_by_id,
            invitation_id=invitation.id,
            source="email",
        )
        ShareClaim.objects.filter(pk=claim.pk).update(created_at=legacy.created_at)
        inbox_item = InboxItem.objects.create(
            owner_id=legacy.accepted_by_id,
            resource_id=resource.id,
            claim_id=claim.id,
            read_at=legacy.created_at if legacy.is_read else None,
            dismissed_at=legacy.created_at if legacy.dismissed or legacy.removed else None,
            is_favorite=legacy.is_favorite,
        )
        InboxItem.objects.filter(pk=inbox_item.pk).update(
            created_at=legacy.created_at,
            updated_at=legacy.created_at,
        )


def reverse_dailyplan_share_backfill(apps, schema_editor):
    ShareResource = apps.get_model("notas", "ShareResource")
    ShareResource.objects.filter(legacy_reference__startswith="dailyplan:").delete()


class Migration(migrations.Migration):
    # PostgreSQL must commit the unique-column index before the legacy-share
    # backfill can enqueue deferred constraint triggers on the sharing tables.
    atomic = False

    dependencies = [
        ('notas', '0056_sharing_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='saved_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='saved_subject_type',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='shareresource',
            name='legacy_reference',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(backfill_accepted_dailyplan_shares, reverse_dailyplan_share_backfill),
    ]
