# Generated by Django 6.0.8 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0057_sharing_inbox_migration_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareinvitation",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shareinvitation",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shareinvitation",
            name="subject",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
