# Generated by Django 6.0.8 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0058_shareinvitation_delivery_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareresource",
            name="last_previewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shareresource",
            name="preview_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
