# Generated by Django 6.0.8 on 2026-09-23 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0064_aiassistantmessagefeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='culinary_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='program',
            name='nutrition_specification',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CulinaryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
                ('family', models.SlugField(max_length=100)),
                ('meal_kinds', models.JSONField(default=list)),
                ('rules', models.JSONField(default=dict)),
                ('preparation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CulinaryVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
                ('ingredients', models.JSONField(default=list)),
                ('preparation', models.TextField()),
                ('status', models.CharField(choices=[('candidate', 'Candidata'), ('rule_validated', 'Validada por reglas; revisión humana pendiente'), ('human_validated', 'Validada por una persona')], default='candidate', max_length=24)),
                ('rubric', models.JSONField(default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_digest', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notas.culinaryvariant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='notas.culinarytemplate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='culinarytemplate',
            constraint=models.UniqueConstraint(fields=('key', 'version'), name='culinary_template_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='culinaryvariant',
            constraint=models.UniqueConstraint(fields=('template', 'key', 'version'), name='culinary_variant_version_unique'),
        ),
    ]
