# Generated by Django 6.0.8 on 2026-10-08 23:57

from django.conf import settings
from django.db import migrations, models


def classify_existing_meals(apps, schema_editor):
    Meal = apps.get_model("notas", "Meal")
    DailyPlanMeal = apps.get_model("notas", "DailyPlanMeal")
    embedded_meal_ids = DailyPlanMeal.objects.values_list("meal_id", flat=True)
    Meal.objects.filter(id__in=embedded_meal_ids).update(scope="embedded")
    Meal.objects.filter(pending_dailyplan_id__isnull=False).update(scope="embedded")


def restore_library_scope(apps, schema_editor):
    Meal = apps.get_model("notas", "Meal")
    Meal.objects.update(scope="library")


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0069_weightlog_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='scope',
            field=models.CharField(choices=[('library', 'Library'), ('embedded', 'Embedded snapshot')], default='library', max_length=16),
        ),
        migrations.RunPython(classify_existing_meals, restore_library_scope),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['created_by', 'scope', 'is_draft', 'list_order'], name='meal_scope_library_idx'),
        ),
    ]
