from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EnvironmentVariableSpec:
    name: str
    category: str
    value_type: str = "string"
    secret: bool = False
    required_in_production: bool = False

    def as_dict(self) -> dict[str, object]:
        return {
            "name": self.name,
            "category": self.category,
            "value_type": self.value_type,
            "secret": self.secret,
            "required_in_production": self.required_in_production,
        }


_GROUPS = {
    "django": (
        "DJANGO_SETTINGS_MODULE", "SECRET_KEY", "ALLOWED_HOSTS", "CSRF_TRUSTED_ORIGINS",
        "SESSION_COOKIE_SECURE", "CSRF_COOKIE_SECURE", "SECURE_SSL_REDIRECT",
        "SECURE_HSTS_SECONDS", "SECURE_HSTS_INCLUDE_SUBDOMAINS", "SECURE_HSTS_PRELOAD",
        "DATABASE_URL", "CACHE_URL", "RENDER_GIT_COMMIT", "RENDER_SERVICE_NAME",
    ),
    "accounts": (
        "ACCOUNT_EMAIL_VERIFICATION", "NUTRITION_ONBOARDING_GATE_ENABLED",
        "RATE_LIMIT_LOGIN", "RATE_LIMIT_SIGNUP", "RATE_LIMIT_SIGNUP_IP_DAILY",
        "RATE_LIMIT_SIGNUP_EMAIL_DAILY", "TURNSTILE_ENABLED", "TURNSTILE_SITE_KEY",
        "TURNSTILE_SECRET_KEY", "TURNSTILE_EXPECTED_ACTION",
        "TURNSTILE_EXPECTED_HOSTNAME", "TURNSTILE_TIMEOUT_SECONDS",
    ),
    "email": (
        "EMAIL_BACKEND", "EMAIL_HOST", "EMAIL_PORT", "EMAIL_HOST_USER",
        "EMAIL_HOST_PASSWORD", "EMAIL_USE_SSL", "EMAIL_USE_TLS", "EMAIL_TIMEOUT",
        "DEFAULT_FROM_EMAIL", "SERVER_EMAIL", "EMAIL_SHARE_DELIVERY_ENABLED",
        "EMAIL_SHARE_DAILY_BUDGET", "EMAIL_SHARE_USER_DAILY_LIMIT",
        "EMAIL_SHARE_RECIPIENT_DAILY_LIMIT",
        "EMAIL_SHARE_RECIPIENT_COOLDOWN_SECONDS",
    ),
    "ai_assistant": (
        "AI_ASSISTANT_CHAT_ENGINE_MODE", "AI_ASSISTANT_LLM_PROVIDER",
        "AI_ASSISTANT_OPENAI_API_KEY", "AI_ASSISTANT_OPENAI_MODEL",
        "AI_ASSISTANT_OPENAI_BASE_URL", "AI_ASSISTANT_OPENAI_TIMEOUT_SECONDS",
        "AI_ASSISTANT_OPENAI_REASONING_EFFORT", "AI_ASSISTANT_USAGE_OBSERVABILITY_ENABLED",
        "AI_ASSISTANT_LLM_PRICING_USD_PER_1M_TOKENS_JSON",
        "AI_ASSISTANT_MODEL_EVALUATION_CANDIDATES_JSON",
        "AI_ASSISTANT_MAX_HISTORY_MESSAGES", "AI_ASSISTANT_MAX_OUTPUT_TOKENS",
        "AI_ASSISTANT_MAX_TOOL_LOOP_ITERATIONS", "AI_ASSISTANT_MAX_INPUT_TOKENS",
        "AI_ASSISTANT_MAX_CONTEXT_CHARS", "AI_ASSISTANT_MAX_MESSAGE_CHARS",
        "AI_ASSISTANT_MAX_TOOL_REQUESTS_PER_TURN",
        "AI_ASSISTANT_ENABLE_REVIEWABLE_PROPOSAL_TOOLS", "AI_ASSISTANT_CREDITS_ENABLED",
        "AI_ASSISTANT_USD_PER_AI_CREDIT", "AI_ASSISTANT_DEFAULT_CREDITS_PER_TURN",
        "AI_ASSISTANT_ASYNC_ENABLED", "AI_ASYNC_JOB_MAX_ATTEMPTS",
        "AI_ASYNC_JOB_LEASE_SECONDS",
        "NUTRITION_LABEL_AI_CREDITS_PER_SCAN", "NUTRITION_LABEL_AI_PRIMARY_MODEL",
        "NUTRITION_LABEL_AI_ESCALATION_MODEL", "NUTRITION_LABEL_AI_TIMEOUT_SECONDS",
        "NUTRITION_LABEL_AI_MAX_IMAGE_BYTES",
        "RATE_LIMIT_AI_ASSISTANT_TURN_USER", "RATE_LIMIT_AI_ASSISTANT_TURN_IP",
        "RATE_LIMIT_NUTRITION_LABEL_SCAN_USER",
    ),
    "nutrition_solver": (
        "NUTRITION_SOLVER_BACKEND", "NUTRITION_SOLVER_SHADOW_ENABLED",
        "NUTRITION_SOLVER_SHADOW_BACKEND", "NUTRITION_SOLVER_TIME_LIMIT_MS",
    ),
    "observability": (
        "SENTRY_DSN", "SENTRY_ENVIRONMENT", "SENTRY_RELEASE",
        "SENTRY_TRACES_SAMPLE_RATE", "SENTRY_PROFILES_SAMPLE_RATE",
    ),
    "food_catalog": (
        "FOOD_CATALOG_FATSECRET_ENABLED", "FOOD_CATALOG_FATSECRET_CLIENT_ID",
        "FOOD_CATALOG_FATSECRET_CLIENT_SECRET", "FOOD_CATALOG_FATSECRET_TOKEN_URL",
        "FOOD_CATALOG_FATSECRET_API_BASE_URL", "FOOD_CATALOG_FATSECRET_OAUTH_SCOPE",
        "FOOD_CATALOG_FATSECRET_SEARCH_METHOD", "FOOD_CATALOG_FATSECRET_FOOD_GET_METHOD",
        "FOOD_CATALOG_FATSECRET_TIMEOUT_SECONDS", "FOOD_CATALOG_OPEN_FOOD_FACTS_ENABLED",
        "FOOD_CATALOG_OPEN_FOOD_FACTS_API_BASE_URL",
        "FOOD_CATALOG_OPEN_FOOD_FACTS_TIMEOUT_SECONDS",
        "FOOD_CATALOG_OPEN_FOOD_FACTS_USER_AGENT",
    ),
    "notifications": (
        "MYSCOOPE_WEB_PUSH_ENABLED", "MYSCOOPE_VAPID_PUBLIC_KEY",
        "MYSCOOPE_VAPID_PRIVATE_KEY", "MYSCOOPE_VAPID_SUBJECT",
        "MYSCOOPE_PWA_CACHE_VERSION",
        "MYSCOOPE_APNS_ENABLED", "MYSCOOPE_APNS_KEY_ID", "MYSCOOPE_APNS_TEAM_ID",
        "MYSCOOPE_APNS_PRIVATE_KEY", "MYSCOOPE_APNS_BUNDLE_ID", "MYSCOOPE_APNS_TIMEOUT_SECONDS",
    ),
    "billing": (
        "BILLING_MERCADOPAGO_WEBHOOK_ENABLED", "BILLING_MERCADOPAGO_CHECKOUT_ENABLED",
        "BILLING_PUBLIC_BASE_URL", "BILLING_MERCADOPAGO_ACCESS_TOKEN",
        "BILLING_MERCADOPAGO_WEBHOOK_SECRET", "BILLING_MERCADOPAGO_API_BASE_URL",
        "BILLING_MERCADOPAGO_TIMEOUT_SECONDS", "BILLING_MERCADOPAGO_WEBHOOK_TOLERANCE_SECONDS",
        "BILLING_APPLE_NOTIFICATIONS_ENABLED", "BILLING_APPLE_PURCHASES_ENABLED",
        "BILLING_APPLE_ENVIRONMENT", "BILLING_APPLE_BUNDLE_ID", "BILLING_APPLE_APP_ID",
        "BILLING_APPLE_IN_APP_PURCHASE_KEY", "BILLING_APPLE_KEY_ID", "BILLING_APPLE_ISSUER_ID",
        "BILLING_APPLE_ONLINE_CHECKS",
        "BILLING_OPENFACTURA_ENABLED", "BILLING_OPENFACTURA_API_KEY",
        "BILLING_OPENFACTURA_API_BASE_URL",
        "BILLING_OPENFACTURA_TIMEOUT_SECONDS", "BILLING_OPENFACTURA_ISSUER_JSON",
    ),
}

_BOOLEAN_NAMES = {
    "SESSION_COOKIE_SECURE", "CSRF_COOKIE_SECURE", "SECURE_SSL_REDIRECT",
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", "SECURE_HSTS_PRELOAD", "EMAIL_USE_SSL",
    "EMAIL_USE_TLS", "EMAIL_SHARE_DELIVERY_ENABLED", "TURNSTILE_ENABLED",
    "NUTRITION_ONBOARDING_GATE_ENABLED", "AI_ASSISTANT_USAGE_OBSERVABILITY_ENABLED",
    "AI_ASSISTANT_ENABLE_REVIEWABLE_PROPOSAL_TOOLS", "AI_ASSISTANT_CREDITS_ENABLED",
    "AI_ASSISTANT_ASYNC_ENABLED",
    "NUTRITION_SOLVER_SHADOW_ENABLED",
    "FOOD_CATALOG_FATSECRET_ENABLED", "FOOD_CATALOG_OPEN_FOOD_FACTS_ENABLED",
    "MYSCOOPE_WEB_PUSH_ENABLED", "MYSCOOPE_APNS_ENABLED", "BILLING_MERCADOPAGO_WEBHOOK_ENABLED",
    "BILLING_MERCADOPAGO_CHECKOUT_ENABLED",
    "BILLING_APPLE_NOTIFICATIONS_ENABLED", "BILLING_APPLE_PURCHASES_ENABLED",
    "BILLING_APPLE_ONLINE_CHECKS",
    "BILLING_OPENFACTURA_ENABLED",
}
_INTEGER_NAMES = {
    "SECURE_HSTS_SECONDS", "EMAIL_PORT", "EMAIL_TIMEOUT", "AI_ASSISTANT_OPENAI_TIMEOUT_SECONDS",
    "AI_ASSISTANT_MAX_HISTORY_MESSAGES", "AI_ASSISTANT_MAX_OUTPUT_TOKENS",
    "AI_ASSISTANT_MAX_TOOL_LOOP_ITERATIONS", "AI_ASSISTANT_MAX_INPUT_TOKENS",
    "AI_ASSISTANT_MAX_CONTEXT_CHARS", "AI_ASSISTANT_MAX_MESSAGE_CHARS",
    "AI_ASSISTANT_MAX_TOOL_REQUESTS_PER_TURN", "AI_ASSISTANT_DEFAULT_CREDITS_PER_TURN",
    "AI_ASYNC_JOB_MAX_ATTEMPTS", "AI_ASYNC_JOB_LEASE_SECONDS",
    "NUTRITION_LABEL_AI_CREDITS_PER_SCAN", "NUTRITION_LABEL_AI_TIMEOUT_SECONDS",
    "NUTRITION_LABEL_AI_MAX_IMAGE_BYTES",
    "NUTRITION_SOLVER_TIME_LIMIT_MS",
    "FOOD_CATALOG_FATSECRET_TIMEOUT_SECONDS", "FOOD_CATALOG_OPEN_FOOD_FACTS_TIMEOUT_SECONDS",
    "BILLING_MERCADOPAGO_TIMEOUT_SECONDS", "BILLING_MERCADOPAGO_WEBHOOK_TOLERANCE_SECONDS",
    "BILLING_APPLE_APP_ID",
    "BILLING_OPENFACTURA_TIMEOUT_SECONDS", "TURNSTILE_TIMEOUT_SECONDS",
    "MYSCOOPE_APNS_TIMEOUT_SECONDS",
    "EMAIL_SHARE_DAILY_BUDGET", "EMAIL_SHARE_USER_DAILY_LIMIT",
    "EMAIL_SHARE_RECIPIENT_DAILY_LIMIT",
    "EMAIL_SHARE_RECIPIENT_COOLDOWN_SECONDS",
}
_FLOAT_NAMES = {"SENTRY_TRACES_SAMPLE_RATE", "SENTRY_PROFILES_SAMPLE_RATE"}
_JSON_NAMES = {
    "AI_ASSISTANT_LLM_PRICING_USD_PER_1M_TOKENS_JSON",
    "AI_ASSISTANT_MODEL_EVALUATION_CANDIDATES_JSON",
}
_SECRET_NAMES = {
    "SECRET_KEY", "DATABASE_URL", "CACHE_URL", "EMAIL_HOST_PASSWORD", "SENTRY_DSN",
    "AI_ASSISTANT_OPENAI_API_KEY",
    "FOOD_CATALOG_FATSECRET_CLIENT_ID", "FOOD_CATALOG_FATSECRET_CLIENT_SECRET",
    "MYSCOOPE_VAPID_PRIVATE_KEY", "MYSCOOPE_APNS_PRIVATE_KEY", "BILLING_MERCADOPAGO_ACCESS_TOKEN",
    "BILLING_MERCADOPAGO_WEBHOOK_SECRET", "BILLING_OPENFACTURA_API_KEY",
    "BILLING_APPLE_IN_APP_PURCHASE_KEY",
    "TURNSTILE_SECRET_KEY",
}
_PRODUCTION_REQUIRED = {"SECRET_KEY", "DATABASE_URL", "ALLOWED_HOSTS"}


def _value_type(name: str) -> str:
    if name in _BOOLEAN_NAMES:
        return "boolean"
    if name in _INTEGER_NAMES:
        return "integer"
    if name in _FLOAT_NAMES:
        return "float"
    if name in _JSON_NAMES:
        return "json"
    return "string"


ENVIRONMENT_VARIABLE_SPECS = tuple(
    EnvironmentVariableSpec(
        name=name,
        category=category,
        value_type=_value_type(name),
        secret=name in _SECRET_NAMES,
        required_in_production=name in _PRODUCTION_REQUIRED,
    )
    for category, names in _GROUPS.items()
    for name in names
)

ENVIRONMENT_VARIABLE_SPEC_BY_NAME = {spec.name: spec for spec in ENVIRONMENT_VARIABLE_SPECS}
