# Generated by My Scoope Patch 56.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period", models.CharField(db_index=True, max_length=7)),
                ("conversation_id", models.CharField(blank=True, max_length=80)),
                ("turn_id", models.CharField(blank=True, max_length=80)),
                ("action_type", models.CharField(db_index=True, max_length=80)),
                ("provider", models.CharField(blank=True, max_length=60)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("cached_input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_cost_usd", models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("error", "Error")],
                        db_index=True,
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("error_type", models.CharField(blank=True, max_length=120)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("tool_calls_count", models.PositiveIntegerField(default=0)),
                ("usage_payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="aiusageevent",
            index=models.Index(fields=["user", "period"], name="ai_usage_user_period_idx"),
        ),
        migrations.AddIndex(
            model_name="aiusageevent",
            index=models.Index(fields=["action_type", "created_at"], name="ai_usage_action_created_idx"),
        ),
        migrations.AddIndex(
            model_name="aiusageevent",
            index=models.Index(fields=["provider", "model_name"], name="ai_usage_provider_model_idx"),
        ),
    ]
