# Generated by My Scoope Patch 58.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusageevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("blocked", "Blocked"),
                ],
                db_index=True,
                default="completed",
                max_length=20,
            ),
        ),
    ]
