# Generated by ChatGPT for Patch 59.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_assistant", "0002_aiusageevent_blocked_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusageevent",
            name="charged_credits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aiusageevent",
            name="credit_plan_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="AIUserCreditQuota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period", models.CharField(db_index=True, max_length=7)),
                ("plan_code", models.CharField(db_index=True, max_length=50)),
                ("monthly_credit_limit", models.PositiveIntegerField(default=0)),
                ("daily_credit_limit", models.PositiveIntegerField(default=0)),
                ("credits_used", models.PositiveIntegerField(default=0)),
                ("hard_blocked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_credit_quotas", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-period", "user_id"],
            },
        ),
        migrations.CreateModel(
            name="AICreditLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period", models.CharField(db_index=True, max_length=7)),
                ("plan_code", models.CharField(db_index=True, max_length=50)),
                ("action_type", models.CharField(db_index=True, max_length=80)),
                ("kind", models.CharField(choices=[("charge", "Charge"), ("adjustment", "Adjustment")], default="charge", max_length=20)),
                ("credits", models.PositiveIntegerField()),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("usage_event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="credit_ledger_entries", to="ai_assistant.aiusageevent")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ai_credit_ledger_entries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="aiusercreditquota",
            constraint=models.UniqueConstraint(fields=("user", "period"), name="ai_credit_quota_user_period_unique"),
        ),
        migrations.AddIndex(
            model_name="aiusercreditquota",
            index=models.Index(fields=["period", "plan_code"], name="ai_cr_quota_period_plan_idx"),
        ),
        migrations.AddIndex(
            model_name="aicreditledger",
            index=models.Index(fields=["user", "period"], name="ai_cr_ledger_user_period_idx"),
        ),
        migrations.AddIndex(
            model_name="aicreditledger",
            index=models.Index(fields=["action_type", "created_at"], name="ai_credit_action_created_idx"),
        ),
    ]
