from django.urls import path

from notas.interface.views.dailyplans import (
    dailyplan_fork,
    dailyplan_copy,
    dailyplan_detail,
    dailyplan_list,
    dailyplan_list_reorder,
    dailyplan_list_bulk_delete,
    dailyplan_create,
    dailyplan_configure,
    dailyplan_rename,
    dailyplan_explore_list,
    dailyplan_explore_detail,
    create_meal_for_dailyplan,
    dailyplan_share,
    dailyplan_share_accept,
    dailyplan_share_dismiss,
    dailyplan_shared_list,
    dailyplan_remove,
    dailyplan_save,
    dailyplan_unshare,
    dailyplan_draft_list,
    dailyplan_draft_detail,
    dailyplan_draft_edit,
    dailyplan_shared_detail,
)
from notas.interface.views.dailyplan_meals import (
    dailyplan_meal_detail,
    dailyplan_meal_edit,
    dailyplan_add_meal,
    dailyplanmeal_remove,
    dailyplanmeal_update,
    dailyplanmeal_create_meal,
    dailyplanmeal_reorder,
    dailyplanmeal_save_to_library,
    dailyplanmeal_share,
    dailyplanmeal_share_accept,
    dailyplanmeal_share_detail,
)

urlpatterns = [
    path("dailyplans/<int:pk>/remove/", dailyplan_remove, name="dailyplan_remove"),
    path("dailyplans/shared/<int:share_id>/unshare/", dailyplan_unshare, name="dailyplan_unshare"),
    path("dailyplans/shared/<int:pk>/", dailyplan_shared_detail, name="dailyplan_shared_detail"),
    path("dailyplans/shared/<int:share_id>/dismiss/", dailyplan_share_dismiss, name="dailyplan_share_dismiss"),
    path("dailyplans/shared/", dailyplan_shared_list, name="dailyplan_shared_list"),
    path("dailyplans/<int:dailyplan_id>/save/", dailyplan_save, name="dailyplan_save"),
    path("dailyplans/<int:pk>/share/", dailyplan_share, name="dailyplan_share"),
    path("dailyplans/shared/<uuid:token>/", dailyplan_share_accept, name="dailyplan_share_accept"),
    path("dailyplans/", dailyplan_list, name="dailyplan_list"),
    path("dailyplans/reorder/", dailyplan_list_reorder, name="dailyplan_list_reorder"),
    path("dailyplans/bulk-delete/", dailyplan_list_bulk_delete, name="dailyplan_list_bulk_delete"),
    path("dailyplans/<int:pk>/", dailyplan_detail, name="dailyplan_detail"),
    path("dailyplans/explore/", dailyplan_explore_list, name="dailyplan_explore_list"),
    path("dailyplans/explore/<int:pk>/", dailyplan_explore_detail, name="dailyplan_explore_detail"),
    path("dailyplans/draft/", dailyplan_draft_list, name="dailyplan_draft_list"),
    path("dailyplans/draft/<int:pk>/", dailyplan_draft_detail, name="dailyplan_draft_detail"),
    path("dailyplans/create/", dailyplan_create, name="dailyplan_create"),
    path("dailyplans/<int:pk>/rename/", dailyplan_rename, name="dailyplan_rename"),
    path("dailyplans/<int:pk>/configure/", dailyplan_configure, name="dailyplan_configure"),
    path("dailyplans/<int:pk>/add-meal/", dailyplan_add_meal, name="dailyplan_add_meal"),
    path("dailyplans/<int:dailyplan_id>/fork/", dailyplan_fork, name="dailyplan_fork"),
    path("dailyplans/<int:pk>/copy/", dailyplan_copy, name="dailyplan_copy"),
    path("dailyplans/draft/<int:pk>/edit/", dailyplan_draft_edit, name="dailyplan_draft_edit"),
    path("dailyplans/<int:dailyplan_id>/meals/create/", create_meal_for_dailyplan, name="create_meal_for_dailyplan"),
    path("dailyplans/<int:dailyplan_id>/meals/<int:pk>/", dailyplan_meal_detail, name="dailyplan_meal_detail"),
    path("dailyplans/<int:dailyplan_id>/meals/<int:dailyplanmeal_id>/update/", dailyplanmeal_update, name="dailyplanmeal_update"),
    path("dailyplans/<int:dailyplan_id>/meals/<int:dailyplanmeal_id>/edit/", dailyplan_meal_edit, name="dailyplan_meal_edit"),
    path("dailyplans/<int:dailyplan_id>/meals/<int:dailyplanmeal_id>/remove/", dailyplanmeal_remove, name="dailyplanmeal_remove"),
    path("dailyplans/<int:dailyplan_id>/meals/<int:dailyplanmeal_id>/create/", dailyplanmeal_create_meal, name="dailyplanmeal_create_meal"),
    path("dailyplans/<int:dailyplan_id>/meals/<int:pk>/share/", dailyplanmeal_share, name="dailyplanmeal_share"),
    path("dailyplans/meals/shared/<uuid:token>/", dailyplanmeal_share_accept, name="dailyplanmeal_share_accept"),
    path("dailyplans/meals/shared/<int:share_id>/", dailyplanmeal_share_detail, name="dailyplanmeal_share_detail"),
    path("dailyplans/<int:dailyplan_id>/meals/<int:dailyplanmeal_id>/save-to-library/", dailyplanmeal_save_to_library, name="dailyplanmeal_save_to_library"),
    path("dailyplans/<int:dailyplan_id>/meals/reorder/", dailyplanmeal_reorder, name="dailyplanmeal_reorder"),
]
