from django.urls import path

from notas.interface.views.programs import (
    add_dailyplan_to_program,
    configure_program,
    copy_program,
    fork_program,
    program_add_week,
    program_create,
    program_day_card,
    program_detail,
    program_duplicate_week,
    program_list,
    program_list_bulk_delete,
    program_list_reorder,
    program_remove,
    program_remove_week,
    program_rename,
    program_reorder_weeks,
    program_share,
    remove_dailyplan_from_program,
)

urlpatterns = [
    path("programs/", program_list, name="program_list"),
    path("programs/reorder/", program_list_reorder, name="program_list_reorder"),
    path("programs/bulk-delete/", program_list_bulk_delete, name="program_list_bulk_delete"),
    path("programs/create/", program_create, name="program_create"),
    path("programs/<int:pk>/rename/", program_rename, name="program_rename"),
    path("programs/<int:pk>/configure/", configure_program, name="configure_program"),
    path("programs/<int:pk>/share/", program_share, name="program_share"),
    path("programs/<int:pk>/remove/", program_remove, name="program_remove"),
    path("programs/<int:pk>/add-week/", program_add_week, name="program_add_week"),
    path("programs/<int:pk>/weeks/reorder/", program_reorder_weeks, name="program_reorder_weeks"),
    path("programs/<int:pk>/weeks/<int:week_number>/duplicate/", program_duplicate_week, name="program_duplicate_week"),
    path("programs/<int:pk>/weeks/<int:week_number>/remove/", program_remove_week, name="program_remove_week"),
    path("programs/<int:pk>/add-dailyplan/", add_dailyplan_to_program, name="add_dailyplan_to_program"),
    path("programs/<int:pk>/days/<int:program_day_id>/card/", program_day_card, name="program_day_card"),
    path("programs/<int:pk>/days/<int:program_day_id>/remove/", remove_dailyplan_from_program, name="remove_dailyplan_from_program"),
    path("programs/<int:pk>/", program_detail, name="program_detail"),
    path("programs/<int:program_id>/fork/", fork_program, name="fork_program"),
    path("programs/<int:pk>/copy/", copy_program, name="copy_program"),
]
