"""Controlled tool registry for future AI Assistant orchestration."""

from ai_assistant.application.tools.executor import (
    ReadOnlyToolExecutor,
    ReadOnlyToolExecutorConfig,
    build_default_read_only_tool_dispatch_table,
    execute_read_only_tool,
)
from ai_assistant.application.tools.proposal_executor import (
    ReviewableProposalToolExecutor,
    build_default_reviewable_proposal_tool_dispatch_table,
    execute_reviewable_proposal_tool,
)
from ai_assistant.application.tools.contracts import (
    AssistantToolCategory,
    AssistantToolRegistryError,
    AssistantToolRiskLevel,
    AssistantToolSpec,
)
from ai_assistant.application.tools.registry import (
    ALLOWED_TOOL_SPECS,
    FORBIDDEN_TOOL_NAMES,
    TOOL_COMPARE_DAILYPLAN_TO_TARGETS,
    TOOL_CREATE_NUTRITION_ENGINE_DAILYPLAN_PROPOSAL,
    TOOL_CREATE_NUTRITION_SOLVER_MEAL_PROPOSAL,
    TOOL_CREATE_VALIDATED_DAILYPLAN_BUILD_PROPOSAL,
    TOOL_CREATE_VALIDATED_MEAL_PROPOSAL,
    TOOL_ITERATE_NUTRITION_ENGINE_DAILYPLAN_PROPOSAL,
    TOOL_LIST_OPERATIONAL_FOODS,
    TOOL_LIST_USER_PROPOSALS,
    TOOL_PREVIEW_NUTRITION_SOLVER_CANDIDATES,
    TOOL_READ_DAILYPLAN,
    TOOL_READ_PROPOSAL,
    TOOL_SEARCH_OPERATIONAL_FOODS,
    get_tool_spec,
    is_allowed_tool_name,
    is_forbidden_tool_name,
    list_allowed_tool_specs,
    list_provider_tool_specs,
    normalize_tool_name,
    validate_tool_request,
)

__all__ = [
    "execute_reviewable_proposal_tool",
    "build_default_reviewable_proposal_tool_dispatch_table",
    "ReviewableProposalToolExecutor",
    "execute_read_only_tool",
    "build_default_read_only_tool_dispatch_table",
    "ReadOnlyToolExecutorConfig",
    "ReadOnlyToolExecutor",
    "ALLOWED_TOOL_SPECS",
    "AssistantToolCategory",
    "AssistantToolRegistryError",
    "AssistantToolRiskLevel",
    "AssistantToolSpec",
    "FORBIDDEN_TOOL_NAMES",
    "TOOL_COMPARE_DAILYPLAN_TO_TARGETS",
    "TOOL_CREATE_NUTRITION_ENGINE_DAILYPLAN_PROPOSAL",
    "TOOL_CREATE_NUTRITION_SOLVER_MEAL_PROPOSAL",
    "TOOL_CREATE_VALIDATED_DAILYPLAN_BUILD_PROPOSAL",
    "TOOL_CREATE_VALIDATED_MEAL_PROPOSAL",
    "TOOL_ITERATE_NUTRITION_ENGINE_DAILYPLAN_PROPOSAL",
    "TOOL_LIST_OPERATIONAL_FOODS",
    "TOOL_LIST_USER_PROPOSALS",
    "TOOL_PREVIEW_NUTRITION_SOLVER_CANDIDATES",
    "TOOL_READ_DAILYPLAN",
    "TOOL_READ_PROPOSAL",
    "TOOL_SEARCH_OPERATIONAL_FOODS",
    "get_tool_spec",
    "is_allowed_tool_name",
    "is_forbidden_tool_name",
    "list_allowed_tool_specs",
    "list_provider_tool_specs",
    "normalize_tool_name",
    "validate_tool_request",
]
